services:
  jeu-two-ships:
    build:
      context: ./games/two-ships
      dockerfile: Dockerfile
    ports:
      - "8083:80"

# ;ddskmkm
  jeu-space-invaders:
    build:
      context: ./games/space-invaders
      dockerfile: Dockerfile
    ports:
      - "8084:80"