# Début du Pipeline
# le worflow est tout ce fichier YAML
name: Continuous Delivery
# (Déploiement Continu) : Son rôle est de préparer la mise en ligne.
on:
    # Les triggers sont les événements qui vont déclencher le workflow
  push:
    branches:
      - dev 

jobs:
  deploy_jeu_1_two_ships:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      

      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
  deploy_jeu_2_space_invaders:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' 
    # On ne déploie que si on est sur la branche dev
    defaults:
      run:
        working-directory: ./games/space-invaders
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Installation
        run: npm install

      - name: Build (Traduction TS vers JS)
        run: npm run build --prefix games/space-invaders
      