# Début du Pipeline
# le worflow est tout ce fichier YAML
name: CD for Two Ships

on:
  push:
    branches:
      - dev
      - main 
      
permissions:
  contents: write

jobs:
  deploy_two_ships:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    # On ne déploie que si on est sur la branche dev ou main
    defaults:
      run:
        working-directory: ./games/two-ships
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Installation
        run: npm ci
        
      - name: Build du projet
        run: npm run build -- --base=./
        
      - name: Déploiement GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./games/two-ships/dist
          destination_dir: two-ships 
          keep_files: true
       
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
       
    
      
      
     
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
          
           
  deploy_jeu_2_space_invaders:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    # On ne déploie que si on est sur la branche dev ou main
    defaults:
      run:
        working-directory: ./games/space-invaders
        # aller dans le dossier du jeu pour faire les étapes suivantes
    steps:
      - uses: actions/checkout@v4
        # checkout du code, c'est à dire récupérer le code de la branche courante pour pouvoir travailler dessus
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Installation
        run: |
          rm -rf node_modules package-lock.json
          npm cache clean --force
          npm install
        # installation des dépendances du projet (node_modules)

      - name: Build (Traduction TS vers JS)
        run: npm run build
        # lancement de la build traduction du TS en JS
        
      - name: Debug - Liste des fichiers après build
        run: |
          ls -R
      
      - name: Déploiement sur GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          # la branche sur laquelle on va déployer, elle doit être créée au préalable
          folder: games/space-invaders/build
          # le dossier à déployer, c'est le dossier de build généré par la commande npm run build
          target-folder: space-invaders
          # le dossier cible sur la branche gh-pages, cela permet d'avoir une URL dédiée pour ce jeu