# Début du Pipeline
# Le workflow est tout ce fichier YAML
name: CI for Two Ships
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: games/two-ships

      - name: Run tests
        run: npm run test
        working-directory: games/two-ships

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
       
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
  job_jeu_2_space_invaders_linter_audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./games/space-invaders
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./games/space-invaders/package-lock.json
        
      - name: Installation des dépendances
        run: npm ci
        # npm ci est une commande optimisée pour les environnements CI, elle installe les dépendances exactement comme spécifié dans le package-lock.json

      - name: Vérification du style (Linter)
        run: npm run lint
        env:
          ESLINT_USE_FLAT_CONFIG: false
        # lancement de liner
    
      - name: Sécurité - Scan des vulnérabilités
        run: npm audit --audit-level=critical || true
        # vérification des vulnérabilités de sécurité dans les dépendances, en échouant si des vulnérabilités de niveau "high" ou supérieur sont trouvées      
        
        
  job_test_jeu_2_space_invaders:
    runs-on: ubuntu-latest
    needs: job_jeu_2_space_invaders_linter_audit
    # ce job ne s'exécutera que si le job de linting et d'audit de sécurité a réussi
    defaults:
      run:
        working-directory: ./games/space-invaders
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Setup Node.js  
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./games/space-invaders/package-lock.json
      
      - name: Installation des dépendances
        run: npm ci
        # npm ci est une commande optimisée pour les environnements CI, elle installe les dépendances exactement comme spécifié dans le package-lock.json
          
      - name: Exécution des tests
        run: npm run test
        # lancement des tests unitaires
         
        
  job_build_jeu_2_space_invaders:
    runs-on: ubuntu-latest
    needs: job_test_jeu_2_space_invaders
    # ce job ne s'exécutera que si le job de test a réussi
    defaults:
      run:
        working-directory: ./games/space-invaders
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./games/space-invaders/package-lock.json
          
      - name: Installation des dépendances
        run: npm ci
        # npm ci est une commande optimisée pour les environnements CI, elle installe les dépendances exactement comme spécifié dans le package-lock.json
        
      - name: Debug - Liste des fichiers
        run: |
          pwd
          ls -R src/
        
        
      - name: Build du projet (Transpilation TS -> JS)
        run: npm run build
        # lancement de la build traduction du TS en JS
        
      - name: Vérification du build
        run: ls -la build/index.html
        # Vérifie que le fichier principal a bien été généré    
