# Début du Pipeline
# le worflow est tout ce fichier YAML
name: Continuous Integration
# (Intégration Continue) : Son rôle est de vérifier la qualité du code.
on:
  # Les triggers sont les événements qui vont déclencher le workflow
  push:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  # c'est le nom du job
  jeu_1_two_ship:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
       
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
  job_jeu_2_space_invaders_linter_audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./games/space-invaders
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./games/space-invaders/package-lock.json
        
      - name: Installation des dépendances
        run: npm ci
        # npm ci est une commande optimisée pour les environnements CI, elle installe les dépendances exactement comme spécifié dans le package-lock.json

      - name: Vérification du style (Linter)
        run: npm run lint
        env:
          ESLINT_USE_FLAT_CONFIG: false
        # lancement de liner
    
      - name: Sécurité - Scan des vulnérabilités
        run: npm audit --audit-level=critical
        # vérification des vulnérabilités de sécurité dans les dépendances, en échouant si des vulnérabilités de niveau "high" ou supérieur sont trouvées      
        
        
  job_test_jeu_2_space_invaders:
    runs-on: ubuntu-latest
    needs: job_jeu_2_space_invaders_linter_audit
    # ce job ne s'exécutera que si le job de linting et d'audit de sécurité a réussi
    defaults:
      run:
        working-directory: ./games/space-invaders
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Setup Node.js  
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./games/space-invaders/package-lock.json
      
      - name: Installation des dépendances
        run: npm ci
        # npm ci est une commande optimisée pour les environnements CI, elle installe les dépendances exactement comme spécifié dans le package-lock.json
          
      - name: Exécution des tests
        run: npm run test
        # lancement des tests unitaires
         
        
  job_build_jeu_2_space_invaders:
    runs-on: ubuntu-latest
    needs: job_test_jeu_2_space_invaders
    # ce job ne s'exécutera que si le job de test a réussi
    defaults:
      run:
        working-directory: ./games/space-invaders
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./games/space-invaders/package-lock.json
          
      - name: Installation des dépendances
        run: npm ci
        # npm ci est une commande optimisée pour les environnements CI, elle installe les dépendances exactement comme spécifié dans le package-lock.json
        
        
      - name: Build du projet (Transpilation TS -> JS)
        run: npm run build
        # lancement de la build traduction du TS en JS
        
      - name: Vérification du build
        run: ls -la build/index.html
        # Vérifie que le fichier principal a bien été généré    
